rule GoFetch
{
    meta:
        description = "Detection patterns for the tool 'GoFetch' taken from the ThreatHunting-Keywords github project"
        author = "@mthcht"
        reference = "https://github.com/mthcht/ThreatHunting-Keywords"
        tool = "GoFetch"
        rule_category = "offensive_tool_keyword"

    strings:
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string1 = /\s\-pathToBloodHoundGraph\s.{0,1000}\s\-pathToOutputGoFetchPath\s.{0,1000}\s\-pathToAdditionalPayload\s/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string2 = /\s\-PathToGraph\s.{0,1000}\.json\s\-PathToPayload\s.{0,1000}\.exe/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string3 = /\/gofetch\.exe/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string4 = /\/GoFetch\.git/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string5 = /\\gofetch\.exe/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string6 = /\\GoFetchLog\.log/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string7 = /\\GoFetch\-main/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string8 = /\\PsExecLog\.log/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string9 = "1615016050f681f61f692ef54d34a26911587fff98fa6ee1f945f1ecd04e2705"
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string10 = "7c37604dd86dc2ce14b352c8df0c4230ab3a1887ef73349806b0e7c15025843c" nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string11 = "BloodHoundGraphToGoFetchPath" nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string12 = "GoFetchAD/GoFetch" nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string13 = "Invoke-GoFetch" nocase ascii wide

    condition:
        any of them
}
