rule GoFetch
{
    meta:
        description = "Detection patterns for the tool 'GoFetch' taken from the ThreatHunting-Keywords github project" 
        author = "@mthcht"
        reference = "https://github.com/mthcht/ThreatHunting-Keywords"
        tool = "GoFetch"
        rule_category = "offensive_tool_keyword"

    strings:
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string1 = /\s\-pathToBloodHoundGraph\s.{0,1000}\s\-pathToOutputGoFetchPath\s.{0,1000}\s\s\-pathToAdditionalPayload\s/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string2 = /\s\-PathToGraph\s.{0,1000}\.json\s\-PathToPayload\s.{0,1000}\.exe/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string3 = /\/GoFetch\.git/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string4 = /\\GoFetchLog\.log/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string5 = /\\PsExecLog\.log/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string6 = /BloodHoundGraphToGoFetchPath/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string7 = /GoFetchAD\/GoFetch/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string8 = /GoFetch\-master/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string9 = /Invoke\-GoFetch/ nocase ascii wide

    condition:
        any of them
}
