rule CamHacker
{
    meta:
        description = "Detection patterns for the tool 'CamHacker' taken from the ThreatHunting-Keywords github project" 
        author = "@mthcht"
        reference = "https://github.com/mthcht/ThreatHunting-Keywords"
        tool = "CamHacker"
        rule_category = "offensive_tool_keyword"

    strings:
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string1 = /\scamhacker\s/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string2 = /\scamhacker\:\/CamHacker/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string3 = /\stermux\-chroot\s.{0,1000}\/cloudflared/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string4 = /\$Hc2\$w\$c\$rQW\$d\$s\$w\$b\$Hc2\$v\$xZp\$f\$w\$V9z\$rQW\$L\$U\$xZp/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string5 = /\$HOME\/\.tunneler/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string6 = /\$N0q\$x\$Hc2\$rQW/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string7 = /\$tunneler_dir\/loclx\.log/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string8 = /\.tunneler\/cf\.log/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string9 = /\.tunneler\/cloudflared/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string10 = /\.tunneler\/loclx/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string11 = /\.tunneler\/loclx\.log/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string12 = /\/\.localxpose\/\.access/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string13 = /\/CamHacker\-.{0,1000}\.png/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string14 = /\/CamHacker\.git/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string15 = /\/releases\/latest\/download\/cloudflared\-darwin\-amd64\.tgz/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string16 = /\[CamHacker\]/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string17 = /\\CamHacker\\/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string18 = /\=ogIXFlckIzYIRCekEHMORiIgwWY2VmCpICcahHJVRCTkcVUyRie5YFJ3RiZkAnW4RidkIzYIRiYkcHJzRCZkcVUyRyYkcHJyMGSkICIsFmdlhCJ9gnC/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string19 = /CamHacker\shas\sa\snew\supdate\!/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string20 = /CamHacker\supdated\ssuccessfully/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string21 = /CamHacker\/releases\/latest\/download\/websites\.zip/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string22 = /Cloudflared\sand\sLoclx\shave\sstarted\ssuccessfully\!/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string23 = /Cloudflared\shas\sstarted\ssuccessfully\!/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string24 = /Device\sarchitecture\sunknown\.\sDownload\scloudflared\/loclx\smanually/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string25 = /Don\'t_blindly_trust_obfuscated_code_it_might_do_something_bad/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string26 = /Enter\syour\sloclx\sauthtoken\:/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string27 = /Hey\sDear\!\sYou\sHave\sWon\sFree\sRs\s399\sJio\sRecharge/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string28 = /https\:\/\/api\.localxpose\.io\/api\/v2\/downloads\/loclx\-darwin\-amd64\.zip/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string29 = /https\:\/\/best\-wishes\-to\-you/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string30 = /https\:\/\/free\-399rs\-jio\-recharge/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string31 = /https\:\/\/join\-zoom\-online\-meeting/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string32 = /https\:\/\/raw\.githubusercontent\.com\/KasRoudra\/CamHacker/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string33 = /https\:\/\/watch\-youtube\-videos\-live/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string34 = /KasRoudra\/CamHacker/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string35 = /kasroudrard\@gmail\.com/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string36 = /Starting\sphp\sserver\sat\slocalhost\:/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string37 = /Tunneling\sfailed\!\sStart\syour\sown\sport\sforwarding\/tunneling\sservice\sat\sport\s/ nocase ascii wide
        // Description: Camera phishing tool. If anyone opens link generated by CamHacker and permits camera access his/her photo will be captured!
        // Reference: https://github.com/KasRoudra/CamHacker
        $string38 = /unzip\swebsites\.zip\s\-d\ssites\s\>\s\/dev\/null/ nocase ascii wide

    condition:
        any of them
}
