rule GoFetch
{
    meta:
        description = "Detection patterns for the tool 'GoFetch' taken from the ThreatHunting-Keywords github project" 
        author = "@mthcht"
        reference = "https://github.com/mthcht/ThreatHunting-Keywords"
        tool = "GoFetch"
        rule_category = "offensive_tool_keyword"

    strings:
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string1 = /.{0,1000}\s\-pathToBloodHoundGraph\s.{0,1000}\s\-pathToOutputGoFetchPath\s.{0,1000}\s\s\-pathToAdditionalPayload\s.{0,1000}/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string2 = /.{0,1000}\s\-PathToGraph\s.{0,1000}\.json\s\-PathToPayload\s.{0,1000}\.exe.{0,1000}/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string3 = /.{0,1000}\/GoFetch\.git.{0,1000}/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string4 = /.{0,1000}\\GoFetchLog\.log.{0,1000}/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string5 = /.{0,1000}\\PsExecLog\.log.{0,1000}/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string6 = /.{0,1000}BloodHoundGraphToGoFetchPath.{0,1000}/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string7 = /.{0,1000}GoFetchAD\/GoFetch.{0,1000}/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string8 = /.{0,1000}GoFetch\-master.{0,1000}/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string9 = /.{0,1000}Invoke\-GoFetch.{0,1000}/ nocase ascii wide

    condition:
        any of them
}
