rule GoFetch
{
    meta:
        description = "Detection patterns for the tool 'GoFetch' taken from the ThreatHunting-Keywords github project" 
        author = "@mthcht"
        reference = "https://github.com/mthcht/ThreatHunting-Keywords"
        tool = "GoFetch"
        rule_category = "offensive_tool_keyword"

    strings:
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string1 = /\s\-pathToBloodHoundGraph\s.{0,100}\s\-pathToOutputGoFetchPath\s.{0,100}\s\s\-pathToAdditionalPayload\s/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string2 = /\s\-PathToGraph\s.{0,100}\.json\s\-PathToPayload\s.{0,100}\.exe/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string3 = /\/GoFetch\.git/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string4 = /\\GoFetchLog\.log/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string5 = /\\PsExecLog\.log/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string6 = /BloodHoundGraphToGoFetchPath/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string7 = /GoFetchAD\/GoFetch/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string8 = /GoFetch\-master/ nocase ascii wide
        // Description: GoFetch is a tool to automatically exercise an attack plan generated by the BloodHound application.
        // Reference: https://github.com/GoFetchAD/GoFetch
        $string9 = /Invoke\-GoFetch/ nocase ascii wide
        $metadata_regex_import = /\bimport\s+[a-zA-Z0-9_.]+\b/ nocase
        $metadata_regex_function = /function\s+[a-zA-Z_][a-zA-Z0-9_]*\(/ nocase ascii
        $metadata_regex_php = /<\?php/ nocase ascii
        $metadata_regex_createobject = /(CreateObject|WScript\.)/ nocase ascii
        $metadata_regex_script = /<script\b/ nocase ascii
        $metadata_regex_javascript = /(let\s|const\s|function\s|document\.|console\.)/ nocase ascii
        $metadata_regex_powershell = /(Write-Host|Get-[a-zA-Z]+|Invoke-|param\(|\.SYNOPSIS)/ nocase ascii
        $metadata_regex_batch = /@(echo\s|call\s|set\s|goto\s|if\s|for\s|rem\s)/ nocase ascii
        $metadata_regex_shebang = /^#!\// nocase ascii

    condition:
        ((filesize < 20MB and (
            uint16(0) == 0x5a4d or // Windows binary
            uint16(0) == 0x457f or // Linux ELF
            uint32be(0) == 0x7f454c46 or uint16(0) == 0xfeca or uint16(0) == 0xfacf or uint32(0) == 0xbebafeca or // macOS binary
            uint32(0) == 0x504B0304 or // Android APK, JAR
            uint32(0) == 0xCAFEBABE or // Java Class, Mach-O Universal Binary
            uint32(0) == 0x4D534346 or // Windows Cabinet File
            uint32(0) == 0xD0CF11E0 or // MSI Installer Package
            uint16(0) == 0x2321 or // Shebang (#!)
            uint16(0) == 0x3c3f // PHP and other script
        )) and any of ($string*)) or
        (filesize < 2MB and
        (
            any of ($string*) and
            for any of ($metadata_regex_*) : ( @ <= 20000 )
        ))
}
